"use client";

import { useMemo, useState } from "react";
import { countRu, formatDate } from "@/lib/format-display";

type Agent = { id: string; name: string; email: string; phone: string; programName: string; results: number; accepted: number; deals: number; acceptanceRate: number; dealRate: number; due: number; paid: number; paidLabel: string; lastActivity: string; score: number };

function downloadBlob(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1_000); }

export function AnalyticsReport({ agents, periodLabel, totals }: { agents: Agent[]; periodLabel: string; totals: { agents: number; active: number; results: number; deals: number; paidLabel: string } }) {
  const [sort, setSort] = useState("score"); const [query, setQuery] = useState("");
  const rows = useMemo(() => agents.filter((agent) => `${agent.name} ${agent.email} ${agent.programName}`.toLowerCase().includes(query.toLowerCase())).sort((left, right) => sort === "deals" ? right.deals - left.deals : sort === "paid" ? right.paid - left.paid : sort === "activity" ? new Date(right.lastActivity).getTime() - new Date(left.lastActivity).getTime() : right.score - left.score), [agents, query, sort]);

  async function exportPdf() {
    const { PDFDocument } = await import("pdf-lib"); const canvas = document.createElement("canvas"); canvas.width = 1240; canvas.height = 1754; const context = canvas.getContext("2d"); if (!context) return;
    context.fillStyle = "#f4f2ea"; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = "#171914"; context.fillRect(0, 0, canvas.width, 210); context.fillStyle = "#b8ff32"; context.font = "800 42px Arial"; context.fillText("RiseStaff", 80, 85); context.fillStyle = "#fff"; context.font = "700 30px Arial"; context.fillText(`Аналитика агентского канала · ${periodLabel}`, 80, 145);
    const metrics = [["АГЕНТЫ", totals.agents], ["ПРИВЕЛИ ЗАЯВКУ", totals.active], ["ЗАЯВКИ", totals.results], ["СДЕЛКИ", totals.deals], ["АГЕНТЫ ПОДТВЕРДИЛИ", totals.paidLabel]]; metrics.forEach(([label, value], index) => { const x = 80 + index % 3 * 360; const y = 280 + Math.floor(index / 3) * 150; context.fillStyle = "#fff"; context.fillRect(x, y, 330, 120); context.fillStyle = "#676a61"; context.font = "700 18px Arial"; context.fillText(String(label), x + 22, y + 34); context.fillStyle = "#171914"; context.font = "800 36px Arial"; context.fillText(String(value), x + 22, y + 82); });
    context.font = "800 34px Arial"; context.fillText("Лидеры", 80, 610); rows.slice(0, 8).forEach((agent, index) => { const y = 670 + index * 115; context.fillStyle = index % 2 ? "#ebe9e1" : "#fff"; context.fillRect(80, y, 1080, 92); context.fillStyle = "#171914"; context.font = "700 24px Arial"; context.fillText(`${index + 1}. ${agent.name || agent.email}`, 105, y + 37); context.font = "20px Arial"; context.fillText(`${countRu(agent.results, "заявка", "заявки", "заявок")} · ${countRu(agent.deals, "сделка", "сделки", "сделок")} · ${agent.paidLabel}`, 105, y + 69); }); context.fillStyle = "#6d7067"; context.font = "18px Arial"; context.fillText(`Сформировано ${new Date().toLocaleString("ru-RU")} · RiseStaff`, 80, 1675);
    const bytes = await fetch(canvas.toDataURL("image/png")).then((response) => response.arrayBuffer()); const pdf = await PDFDocument.create(); const page = pdf.addPage([595.28, 841.89]); const image = await pdf.embedPng(bytes); page.drawImage(image, { x: 0, y: 0, width: 595.28, height: 841.89 }); const saved = await pdf.save(); const pdfBytes = saved.buffer.slice(saved.byteOffset, saved.byteOffset + saved.byteLength) as ArrayBuffer; downloadBlob(new Blob([pdfBytes], { type: "application/pdf" }), "relay-analytics.pdf");
  }

  return <section className="panel analytics-agent-directory"><div className="panel-header"><div><h2>Агенты в выбранной аналитике</h2><p>Карточки заменяют широкую таблицу: сравнивайте вклад и открывайте контакты без горизонтального скролла.</p></div><button type="button" onClick={() => void exportPdf()}>Скачать PDF ↓</button></div><div className="analytics-local-controls"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Найти агента" /><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="score">По общему вкладу</option><option value="deals">По сделкам</option><option value="paid">По выплатам</option><option value="activity">По активности</option></select></div><div className="analytics-agent-cards">{rows.map((agent, index) => <article key={agent.id}><header><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{agent.name || "Имя не указано"}</strong><small>{agent.programName}</small></div><b>{agent.dealRate}%</b></header><div><span><small>ЗАЯВКИ</small><strong>{agent.results}</strong></span><span><small>ПРИНЯТО</small><strong>{agent.accepted}</strong></span><span><small>СДЕЛКИ</small><strong>{agent.deals}</strong></span><span><small>АГЕНТ ПОДТВЕРДИЛ</small><strong>{agent.paidLabel}</strong></span></div><footer><span>Активность {formatDate(agent.lastActivity)}</span><a href={agent.phone ? `https://wa.me/${agent.phone.replace(/\D/g, "")}` : `mailto:${agent.email}`} target={agent.phone ? "_blank" : undefined} rel={agent.phone ? "noreferrer" : undefined}>{agent.phone ? "WhatsApp ↗" : "Email ↗"}</a></footer></article>)}</div>{!rows.length && <div className="table-empty">По выбранным условиям агентов нет.</div>}</section>;
}
