"use client";

import { localizeInterface } from "../../../lib/interface-locale";
import { useMemo, useState } from "react";
import { countRu, formatDate } from "@/lib/format-display";

type Agent = { id: string; name: string; email: string; phone: string; programName: string; results: number; accepted: number; deals: number; acceptanceRate: number; dealRate: number; due: number; paid: number; dueLabel?: string; paidLabel: string; lastActivity: string; score: number };

function downloadBlob(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1_000); }

export function AnalyticsReport({ agents, periodLabel, totals, title = "Агенты в выбранной аналитике", description = "Сравнивайте вклад, конверсию, деньги и активность без широкой таблицы." }: { agents: Agent[]; periodLabel: string; totals: { agents: number; active: number; results: number; deals: number; paidLabel: string }; title?: string; description?: string }) {
  const [sort, setSort] = useState("score");
  const [query, setQuery] = useState("");
  const [activity, setActivity] = useState("ALL");
  const rows = useMemo(() => agents.filter((agent) => {
    const matchesQuery = `${agent.name} ${agent.email} ${agent.phone} ${agent.programName}`.toLowerCase().includes(query.toLowerCase());
    const matchesActivity = activity === "ALL" || (activity === "DEALS" ? agent.deals > 0 : activity === "RESULTS" ? agent.results > 0 : agent.results === 0);
    return matchesQuery && matchesActivity;
  }).sort((left, right) => sort === "deals" ? right.deals - left.deals : sort === "results" ? right.results - left.results : sort === "acceptance" ? right.acceptanceRate - left.acceptanceRate : sort === "conversion" ? right.dealRate - left.dealRate : sort === "paid" ? right.paid - left.paid : sort === "due" ? right.due - left.due : sort === "activity" ? new Date(right.lastActivity).getTime() - new Date(left.lastActivity).getTime() : right.score - left.score), [agents, query, sort, activity]);

  async function exportPdf() {
    const { PDFDocument } = await import("pdf-lib"); const canvas = document.createElement("canvas"); canvas.width = 1240; canvas.height = 1754; const context = canvas.getContext("2d"); if (!context) return;
    context.fillStyle = "#f4f2ea"; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = "#171914"; context.fillRect(0, 0, canvas.width, 210); context.fillStyle = "#b8ff32"; context.font = "800 42px Arial"; context.fillText("RiseStaff", 80, 85); context.fillStyle = "#fff"; context.font = "700 30px Arial"; context.fillText(localizeInterface(`Рейтинг агентов · ${periodLabel}`), 80, 145);
    const metrics = [["АГЕНТЫ", totals.agents], ["ПРИВЕЛИ ЗАЯВКУ", totals.active], ["ЗАЯВКИ", totals.results], ["СДЕЛКИ", totals.deals], ["ПОЛУЧЕНО АГЕНТАМИ", totals.paidLabel]]; metrics.forEach(([label, value], index) => { const x = 80 + index % 3 * 360; const y = 280 + Math.floor(index / 3) * 150; context.fillStyle = "#fff"; context.fillRect(x, y, 330, 120); context.fillStyle = "#676a61"; context.font = "700 18px Arial"; context.fillText(localizeInterface(String(label)), x + 22, y + 34); context.fillStyle = "#171914"; context.font = "800 36px Arial"; context.fillText(String(value), x + 22, y + 82); });
    context.font = "800 34px Arial"; context.fillText(localizeInterface("Лидеры"), 80, 610); rows.slice(0, 8).forEach((agent, index) => { const y = 670 + index * 115; context.fillStyle = index % 2 ? "#ebe9e1" : "#fff"; context.fillRect(80, y, 1080, 92); context.fillStyle = "#171914"; context.font = "700 24px Arial"; context.fillText(`${index + 1}. ${agent.name || agent.email}`, 105, y + 37); context.font = "20px Arial"; context.fillText(localizeInterface(`${countRu(agent.results, "заявка", "заявки", "заявок")} · ${countRu(agent.deals, "сделка", "сделки", "сделок")} · ${agent.paidLabel}`), 105, y + 69); }); context.fillStyle = "#6d7067"; context.font = "18px Arial"; context.fillText(localizeInterface(`Сформировано ${new Date().toLocaleString("ru-RU")} · RiseStaff`), 80, 1675);
    const bytes = await fetch(canvas.toDataURL("image/png")).then((response) => response.arrayBuffer()); const pdf = await PDFDocument.create(); const page = pdf.addPage([595.28, 841.89]); const image = await pdf.embedPng(bytes); page.drawImage(image, { x: 0, y: 0, width: 595.28, height: 841.89 }); const saved = await pdf.save(); const pdfBytes = saved.buffer.slice(saved.byteOffset, saved.byteOffset + saved.byteLength) as ArrayBuffer; downloadBlob(new Blob([pdfBytes], { type: "application/pdf" }), "risestaff-agent-rating.pdf");
  }

  return <section className="panel analytics-agent-directory"><div className="panel-header"><div><h2>{title}</h2><p>{description}</p></div><button type="button" onClick={() => void exportPdf()}>Скачать PDF ↓</button></div><div className="analytics-local-controls rating-controls"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Имя, телефон, email или программа" aria-label="Поиск агента" /><select value={activity} onChange={(event) => setActivity(event.target.value)} aria-label="Фильтр активности"><option value="ALL">Все агенты</option><option value="DEALS">Есть сделки</option><option value="RESULTS">Есть заявки</option><option value="INACTIVE">Нет заявок</option></select><select value={sort} onChange={(event) => setSort(event.target.value)} aria-label="Сортировка рейтинга"><option value="score">По общему вкладу</option><option value="deals">По количеству сделок</option><option value="results">По количеству заявок</option><option value="conversion">По конверсии в сделку</option><option value="acceptance">По качеству заявок</option><option value="paid">По полученным выплатам</option><option value="due">По сумме к выплате</option><option value="activity">По последней активности</option></select></div><div className="rating-formula"><strong>Как считается место</strong><span>Сделка — 100 баллов · принятая заявка — 20 · переданная заявка — 5. Фильтры меняют состав рейтинга, сортировка — порядок.</span></div><div className="analytics-agent-cards rating-agent-cards">{rows.map((agent, index) => <article className={index < 3 ? `rating-place-${index + 1}` : ""} key={agent.id}><header><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{(agent.name) ? (<bdi data-no-translate>{agent.name}</bdi>) : ("Имя не указано")}</strong><small>{<bdi data-no-translate>{agent.programName}</bdi>}</small></div><b>{agent.dealRate}% в сделку</b></header><div><span><small>ЗАЯВКИ</small><strong>{agent.results}</strong></span><span><small>ПРИНЯТО</small><strong>{agent.accepted} · {agent.acceptanceRate}%</strong></span><span><small>СДЕЛКИ</small><strong>{agent.deals}</strong></span><span><small>К ВЫПЛАТЕ</small><strong>{agent.dueLabel || "0"}</strong></span><span><small>ПОЛУЧЕНО</small><strong>{agent.paidLabel}</strong></span><span><small>БАЛЛЫ</small><strong>{agent.score}</strong></span></div><footer><span>Активность {formatDate(agent.lastActivity)}</span><a href={agent.phone ? `https://wa.me/${agent.phone.replace(/\D/g, "")}` : `mailto:${agent.email}`} target={agent.phone ? "_blank" : undefined} rel={agent.phone ? "noreferrer" : undefined}>{agent.phone ? "WhatsApp ↗" : "Email ↗"}</a></footer></article>)}</div>{!rows.length && <div className="table-empty">По выбранным условиям агентов нет.</div>}</section>;
}
