import { notFound } from "next/navigation";
import { getPartnerPortal } from "../../../../db/partner";
import { SafeLink as Link } from "@/app/safe-link";
import { DisputeButton } from "../../_components/partner-actions";
import { shortDate } from "../../_lib";
import { reviewStatusNames, salesStatusNames } from "@/lib/workflow";

export default async function PartnerSubmissionsPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const portal = await getPartnerPortal(token);
  if (!portal) notFound();
  return <div className="partner-portal-content"><div className="partner-page-heading"><div><span>ВАШИ РЕКОМЕНДАЦИИ</span><h1>Лиды и сделки</h1><p>Проверка заявки, движение клиента и выплата показаны отдельно — один этап больше не скрывает другой.</p></div><Link className="button button-primary" href={`/partner/${token}/opportunities`}>Передать новый лид <span>↗</span></Link></div>{portal.submissions.length ? <section className="partner-submission-list">{portal.submissions.map((submission) => { const detailHref = `/partner/${token}/submissions/${submission.id}`; const review = submission.reviewStatus as keyof typeof reviewStatusNames; const sales = submission.salesStatus as keyof typeof salesStatusNames; const payment = submission.reward?.status === "PAID" ? submission.reward.partnerConfirmedAt ? "Деньги получены" : "Компания отметила перевод" : submission.reward?.status === "APPROVED" ? "К выплате" : "Начисления пока нет"; return <article key={submission.id}><div className="submission-card-head"><div><span>ЗАЯВКА #{submission.id.slice(0, 6).toUpperCase()}</span><h2><Link className="submission-company-link" href={detailHref}>{submission.contactName}{submission.contactCompany ? ` · ${submission.contactCompany}` : ""} <small>Открыть данные →</small></Link></h2><p>Передана {new Date(submission.createdAt).toLocaleString("ru-RU")}</p></div><strong className={`partner-status status-${submission.reviewStatus.toLowerCase()}`}>{reviewStatusNames[review]}</strong></div><div className="partner-state-cards"><div><small>ПРОВЕРКА</small><strong>{reviewStatusNames[review]}</strong></div><div><small>ПРОДАЖА</small><strong>{salesStatusNames[sales]}</strong></div><div><small>ВОЗНАГРАЖДЕНИЕ</small><strong>{payment}</strong></div></div>{submission.companyComment && <div className="company-comment"><span>КОММЕНТАРИЙ КОМПАНИИ</span><p>{submission.companyComment}</p></div>}<div className="submission-detail-grid"><div><span>Задание</span><strong>{submission.mission?.title}</strong></div><div><span>Можно заработать</span><strong>{submission.mission?.rewardLabel}</strong></div><div><span>Последнее изменение</span><strong>{shortDate(submission.events[0]?.createdAt || submission.updatedAt)}</strong></div></div><Link className="read-only-result-link" href={detailHref}>Посмотреть переданные данные →</Link><DisputeButton token={token} submissionId={submission.id} opened={Boolean(submission.dispute)} /></article>; })}</section> : <section className="partner-large-empty"><span>↗</span><h2>Рекомендаций пока нет</h2><p>Выберите задание и передайте первый подходящий контакт. После отправки результат сразу появится здесь.</p><Link className="button button-primary" href={`/partner/${token}/opportunities`}>Открыть задания <span>→</span></Link></section>}</div>;
}
