import { notFound } from "next/navigation";
import { getPartnerPortal } from "../../../../db/partner";
import { SafeLink as Link } from "@/app/safe-link";
import { DisputeButton } from "../../_components/partner-actions";
import { shortDate, statusNames } from "../../_lib";

const pipeline = ["SUBMITTED", "REVIEWING", "ACCEPTED", "IN_PROGRESS", "DEAL", "REWARDED"];

export default async function PartnerSubmissionsPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const portal = await getPartnerPortal(token);
  if (!portal) notFound();
  return <div className="partner-portal-content"><div className="partner-page-heading"><div><span>ПРОЗРАЧНАЯ ВОРОНКА</span><h1>Лиды и сделки</h1><p>Кто владеет рекомендацией, что с ней произошло и на каком основании принято решение.</p></div><Link className="button button-primary" href={`/p/${portal.program.slug}?access=${token}`}>Передать новый лид <span>↗</span></Link></div>{portal.submissions.length ? <section className="partner-submission-list">{portal.submissions.map((submission) => { const step = pipeline.indexOf(submission.status); return <article key={submission.id}><div className="submission-card-head"><div><span>ЛИД #{submission.id.slice(0, 6).toUpperCase()}</span><h2>{submission.contactName} · {submission.contactCompany}</h2><p>Зафиксирован {new Date(submission.createdAt).toLocaleString("ru-RU")}</p></div><strong className={`partner-status status-${submission.status.toLowerCase()}`}>{statusNames[submission.status] ?? submission.status}</strong></div><div className="partner-pipeline">{pipeline.map((status, index) => <div className={index <= step ? "done" : ""} key={status}><i>{index < step ? "✓" : index + 1}</i><span>{statusNames[status]}</span></div>)}</div>{submission.companyComment && <div className="company-comment"><span>КОММЕНТАРИЙ КОМПАНИИ</span><p>{submission.companyComment}</p></div>}<div className="submission-detail-grid"><div><span>Миссия</span><strong>{submission.mission?.title}</strong></div><div><span>Вознаграждение</span><strong>{submission.mission?.rewardLabel}</strong></div><div><span>Последнее изменение</span><strong>{shortDate(submission.events[0]?.createdAt || submission.updatedAt)}</strong></div></div>{submission.partnerComment && <p className="partner-own-comment"><strong>Ваш комментарий:</strong> {submission.partnerComment}</p>}{submission.attachments.length > 0 && <div className="partner-attachments"><span>ПРИЛОЖЕНИЯ</span>{submission.attachments.map((attachment) => attachment.externalUrl ? <a href={attachment.externalUrl} target="_blank" rel="noreferrer" referrerPolicy="no-referrer" key={attachment.id}>{attachment.fileName} ↗</a> : <a href={`/api/partner/files/${attachment.id}?token=${token}`} key={attachment.id}>{attachment.fileName} ↓</a>)}</div>}<details className="status-history"><summary>История статусов · {submission.events.length}</summary>{submission.events.map((event) => <div key={event.id}><i>●</i><span>{statusNames[event.toStatus] ?? event.toStatus}<small>{new Date(event.createdAt).toLocaleString("ru-RU")}</small></span><p>{event.comment}</p></div>)}</details><DisputeButton token={token} submissionId={submission.id} opened={Boolean(submission.dispute)} /></article>; })}</section> : <section className="partner-large-empty"><span>↗</span><h2>Рекомендаций пока нет</h2><p>Первый отправленный лид сразу появится здесь со статусом «Отправлен».</p><Link className="button button-primary" href={`/p/${portal.program.slug}?access=${token}`}>Выбрать миссию <span>→</span></Link></section>}</div>;
}
