import { notFound } from "next/navigation";
import { getPartnerPortal } from "../../../../db/partner";
import { SafeLink as Link } from "@/app/safe-link";
import { DisputeButton } from "../../_components/partner-actions";
import { shortDate, statusNames } from "../../_lib";

const pipeline = ["SUBMITTED", "REVIEWING", "ACCEPTED", "IN_PROGRESS", "DEAL", "REWARDED"];

export default async function PartnerSubmissionsPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const portal = await getPartnerPortal(token);
  if (!portal) notFound();
  return <div className="partner-portal-content"><div className="partner-page-heading"><div><span>ВАШИ РЕКОМЕНДАЦИИ</span><h1>Лиды и сделки</h1><p>Здесь видно, что произошло с каждым результатом, какое решение приняла компания и когда изменился статус.</p></div><Link className="button button-primary" href={`/partner/${token}/opportunities`}>Передать новый лид <span>↗</span></Link></div>{portal.submissions.length ? <section className="partner-submission-list">{portal.submissions.map((submission) => { const step = pipeline.indexOf(submission.status); const detailHref = `/partner/${token}/submissions/${submission.id}`; return <article key={submission.id}><div className="submission-card-head"><div><span>ЛИД #{submission.id.slice(0, 6).toUpperCase()}</span><h2><Link className="submission-company-link" href={detailHref}>{submission.contactName}{submission.contactCompany ? ` · ${submission.contactCompany}` : ""} <small>Открыть данные →</small></Link></h2><p>Передан {new Date(submission.createdAt).toLocaleString("ru-RU")}</p></div><strong className={`partner-status status-${submission.status.toLowerCase()}`}>{statusNames[submission.status] ?? submission.status}</strong></div><div className="partner-pipeline">{pipeline.map((status, index) => <div className={index <= step ? "done" : ""} key={status}><i>{index < step ? "✓" : index + 1}</i><span>{statusNames[status]}</span></div>)}</div>{submission.companyComment && <div className="company-comment"><span>КОММЕНТАРИЙ КОМПАНИИ</span><p>{submission.companyComment}</p></div>}<div className="submission-detail-grid"><div><span>Задание</span><strong>{submission.mission?.title}</strong></div><div><span>Можно заработать</span><strong>{submission.mission?.rewardLabel}</strong></div><div><span>Последнее изменение</span><strong>{shortDate(submission.events[0]?.createdAt || submission.updatedAt)}</strong></div></div><Link className="read-only-result-link" href={detailHref}>Посмотреть переданные данные →</Link><DisputeButton token={token} submissionId={submission.id} opened={Boolean(submission.dispute)} /></article>; })}</section> : <section className="partner-large-empty"><span>↗</span><h2>Рекомендаций пока нет</h2><p>Выберите задание и передайте первый подходящий контакт. После отправки результат сразу появится здесь.</p><Link className="button button-primary" href={`/partner/${token}/opportunities`}>Открыть возможности <span>→</span></Link></section>}</div>;
}
