import { notFound } from "next/navigation";
import { getPartnerPortal } from "../../../../db/partner";
import { CopyTextButton } from "../../_components/partner-actions";

const kindNames: Record<string, string> = { SCRIPT: "ГОТОВЫЙ СКРИПТ", GUIDE: "ИНСТРУКЦИЯ", CASE: "КЕЙС", LINK: "ПОЛЕЗНАЯ ССЫЛКА", FILE: "ФАЙЛ" };

export default async function MaterialsPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const portal = await getPartnerPortal(token);
  if (!portal) notFound();
  const instagram = portal.company.contactInstagram.replace(/^@/, "");
  const whatsappDigits = portal.company.contactWhatsapp.replace(/\D/g, "");

  return <div className="partner-portal-content knowledge-base-page"><div className="partner-page-heading"><div><span>БАЗА ЗНАНИЙ</span><h1>Всё, чтобы уверенно представлять {portal.company.name}</h1><p>Контакты компании, готовые скрипты, инструкции, ссылки и файлы собраны в одном месте.</p></div></div><section className="agent-company-overview"><div><small>ВЫ ПРЕДСТАВЛЯЕТЕ</small><h2>{portal.company.name}</h2><p>{portal.companyProfile?.businessDescription || portal.program.description || "Описание компании пока не добавлено."}</p></div><nav><a href={portal.company.website} target="_blank" rel="noreferrer">Сайт компании <span>↗</span></a>{instagram ? <a href={`https://instagram.com/${instagram}`} target="_blank" rel="noreferrer">Instagram @{instagram} <span>↗</span></a> : <span>Instagram не указан компанией</span>}{whatsappDigits ? <a href={`https://wa.me/${whatsappDigits}?text=${encodeURIComponent(`Здравствуйте! Я агент компании ${portal.company.name} в Relay.`)}`} target="_blank" rel="noreferrer">WhatsApp компании <span>↗</span></a> : <span>WhatsApp не указан компанией</span>}</nav></section>{portal.knowledgeItems.length ? <section className="company-knowledge-grid">{portal.knowledgeItems.map((item) => <article key={item.id}><span>{kindNames[item.kind] || "МАТЕРИАЛ"}</span><h2>{item.title}</h2>{item.content && <p>{item.content}</p>}<div>{item.content && <CopyTextButton text={item.content} label="Скопировать" />}{item.externalUrl && <a href={item.externalUrl} target="_blank" rel="noreferrer">Открыть ссылку ↗</a>}{item.objectKey && <a href={`/api/partner/knowledge/${item.id}?token=${token}`}>Скачать {item.fileName || "файл"} ↓</a>}</div></article>)}</section> : <section className="partner-large-empty"><span>▤</span><h2>Компания ещё готовит материалы</h2><p>Пока используйте условия заданий и контакты компании выше.</p></section>}<section className="materials-grid">{portal.missions.map((mission) => { const intro = `Здравствуйте! Хочу познакомить вас с компанией ${portal.company.name}. Возможно, вам будет полезно: «${mission.title.toLowerCase()}». Если актуально, организую короткое знакомство без обязательств.`; return <article key={mission.id}><span>{mission.programName}</span><h2>{mission.title}</h2><div className="knowledge-reward"><small>МОЖНО ЗАРАБОТАТЬ</small><strong>{mission.rewardLabel}</strong></div><blockquote>{intro}</blockquote><CopyTextButton text={intro} label="Скопировать сообщение" /><div><strong>Кого искать</strong><p>{mission.description}</p></div><div><strong>Что уточнить</strong>{mission.instructions.length ? <ul>{mission.instructions.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Следуйте условиям задания.</p>}</div></article>; })}</section></div>;
}
