import { notFound } from "next/navigation";
import { getPartnerPortal } from "../../../../db/partner";
import { CopyTextButton } from "../../_components/partner-actions";

export default async function KnowledgeBasePage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const portal = await getPartnerPortal(token);
  if (!portal) notFound();
  const whatsappDigits = portal.company.contactWhatsapp.replace(/\D/g, "");
  const instagram = portal.company.contactInstagram.replace(/^@/, "");
  return <div className="partner-portal-content knowledge-base-page"><div className="partner-page-heading"><div><span>БАЗА ЗНАНИЙ</span><h1>Всё, чтобы уверенно рекомендовать компанию</h1><p>Коротко о компании, прямые контакты и готовые материалы для первого сообщения потенциальному клиенту.</p></div></div><section className="agent-company-overview"><div><small>ВЫ ПРЕДСТАВЛЯЕТЕ</small><h2>{portal.company.name}</h2><p>{portal.companyProfile?.businessDescription || portal.program.description || "Описание компании пока не добавлено."}</p></div><nav><a href={portal.company.website} target="_blank" rel="noreferrer">Сайт компании <span>↗</span></a>{instagram ? <a href={`https://instagram.com/${instagram}`} target="_blank" rel="noreferrer">Instagram @{instagram} <span>↗</span></a> : <span>Instagram не указан компанией</span>}{whatsappDigits ? <a href={`https://wa.me/${whatsappDigits}?text=${encodeURIComponent(`Здравствуйте! Я агент компании ${portal.company.name} в Relay.`)}`} target="_blank" rel="noreferrer">WhatsApp компании <span>↗</span></a> : <span>WhatsApp не указан компанией</span>}</nav></section><section className="knowledge-company-facts"><article><small>ЧТО ПРЕДЛАГАЕТ КОМПАНИЯ</small><p>{portal.companyProfile?.partnerPitch || portal.program.description || "Изучите описания заданий ниже."}</p></article><article><small>КОМУ ПОДХОДИТ</small><p>{portal.companyProfile?.targetAudience || "Критерии подходящего клиента указаны в каждом задании."}</p></article></section><section className="materials-grid">{portal.missions.map((mission) => { const intro = `Здравствуйте! Хочу познакомить вас с компанией ${portal.company.name}. Компания помогает решить задачу: «${mission.title.toLowerCase()}». Если это актуально, могу организовать короткое знакомство без обязательств.`; return <article key={mission.id}><span>МАТЕРИАЛЫ К ЗАДАНИЮ</span><h2>{mission.title}</h2><div className="knowledge-reward"><small>ВОЗНАГРАЖДЕНИЕ АГЕНТА</small><strong>{mission.rewardLabel}</strong></div><blockquote>{intro}</blockquote><CopyTextButton text={intro} label="Скопировать сообщение" /><div><strong>Кого искать</strong><p>{mission.description}</p></div><div><strong>Что уточнить</strong>{mission.instructions.length ? <ul>{mission.instructions.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Следуйте условиям задания.</p>}</div><div><strong>Что приложить</strong>{mission.proofRequirements.length ? <ul>{mission.proofRequirements.map((item) => <li key={item}>{item}</li>)}</ul> : <p>Дополнительные материалы не требуются.</p>}</div><div><strong>Нейтральный ответ на возражение</strong><p>«Я не продаю вам продукт — только знакомлю с командой. Решение о разговоре всегда остаётся за вами».</p></div></article>; })}</section>{!portal.missions.length && <section className="partner-large-empty"><span>▤</span><h2>Материалы ещё не опубликованы</h2><p>Когда компания добавит задания, здесь появятся готовые сообщения и критерии подходящего клиента.</p></section>}</div>;
}
