"use client";

import { SafeLink as Link } from "@/app/safe-link";
import { useMemo, useRef, useState } from "react";
import type { MissionRecord, ProgramRecord } from "../../../../db/programs";
import { agentUrl } from "../../../../lib/public-origins";

const typeNames: Record<string, string> = { LEAD: "Люди", DEAL: "Сделки", IMAGE: "Имидж", ENGAGEMENT: "Вовлечение" };
const typeIcons: Record<string, string> = { LEAD: "↗", DEAL: "◇", IMAGE: "◎", ENGAGEMENT: "✦" };
const typeCopy: Record<string, { summary: string; result: string; proof: string; template: Omit<MissionRecord, "id" | "sortOrder" | "resources"> }> = {
  LEAD: { summary: "Новый подходящий контакт или знакомство", result: "Кого и с какими данными нужно передать", proof: "Какие данные или документы подтверждают качество контакта", template: { type: "LEAD", title: "Познакомьте с подходящей компанией", description: "Передайте контакт человека, который соответствует портрету клиента и согласен на знакомство.", instructions: ["Найдите подходящего потенциального клиента", "Получите согласие на передачу контакта", "Передайте имя, компанию и телефон через Relay"], proofRequirements: ["Имя и рабочий телефон", "Комментарий: почему клиент подходит"], rewardMode: "FIXED", rewardValue: 0, rewardLabel: "Укажите награду за принятый контакт", verificationRules: "Компания проверит соответствие портрету клиента, согласие на контакт и отсутствие дубликата.", status: "ACTIVE" } },
  DEAL: { summary: "Оплаченная сделка или подтверждённый договор", result: "Какой коммерческий результат должен состояться", proof: "Какие документы подтверждают договорённость или оплату", template: { type: "DEAL", title: "Помогите довести клиента до сделки", description: "Сопроводите знакомство до согласованного коммерческого результата: договора, оплаты или подписки.", instructions: ["Организуйте знакомство с ответственным лицом", "Помогите согласовать следующий коммерческий шаг", "Передайте подтверждение результата через Relay"], proofRequirements: ["Номер договора, счёта или подтверждение оплаты", "Комментарий о роли агента в сделке"], rewardMode: "PERCENT", rewardValue: 0, rewardLabel: "Укажите процент или сумму за сделку", verificationRules: "Награда подтверждается после зафиксированного в условиях программы коммерческого события.", status: "ACTIVE" } },
  IMAGE: { summary: "Публикация, кейс, отзыв или полезное упоминание", result: "Какой публичный материал должен появиться", proof: "Ссылка, скриншот или файл опубликованного материала", template: { type: "IMAGE", title: "Расскажите о продукте своей аудитории", description: "Создайте полезную публикацию, кейс или отзыв, который честно показывает ценность продукта.", instructions: ["Выберите подходящий формат и площадку", "Подготовьте материал без неподтверждённых обещаний", "Опубликуйте и передайте ссылку через Relay"], proofRequirements: ["Ссылка на публикацию", "Скриншот или файл материала"], rewardMode: "FIXED", rewardValue: 0, rewardLabel: "Укажите награду после проверки публикации", verificationRules: "Компания проверит соответствие брифу, факт публикации и доступность материала аудитории.", status: "ACTIVE" } },
  ENGAGEMENT: { summary: "Обучение, мероприятие, тест или активность", result: "Какое полезное действие должен выполнить агент", proof: "Результат теста, скриншот или подтверждение участия", template: { type: "ENGAGEMENT", title: "Выполните полезную продуктовую активность", description: "Пройдите обучение, посетите событие или выполните действие, которое помогает лучше работать с продуктом.", instructions: ["Откройте материал или событие", "Выполните указанную активность", "Передайте подтверждение через Relay"], proofRequirements: ["Скриншот результата или подтверждение участия"], rewardMode: "NON_MONETARY", rewardValue: 0, rewardLabel: "Откройте доступ к новым заданиям", verificationRules: "Компания проверит завершение активности по указанному подтверждению.", status: "ACTIVE" } },
};

function downloadBlob(blob: Blob, name: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }

export function ProgramEditor({ initialProgram }: { initialProgram: ProgramRecord }) {
  const [program, setProgram] = useState(initialProgram);
  const [activeType, setActiveType] = useState(initialProgram.missions[0]?.type || "LEAD");
  const [activeMissionId, setActiveMissionId] = useState(initialProgram.missions[0]?.id || "");
  const [pending, setPending] = useState<"save" | "publish" | "pause" | null>(null);
  const [fileBusy, setFileBusy] = useState(false);
  const [notice, setNotice] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const [publicUrl, setPublicUrl] = useState(program.status === "ACTIVE" ? agentUrl(`/p/${program.slug}`) : null);
  const [qrUrl, setQrUrl] = useState("");
  const [showQr, setShowQr] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);
  const typeMissions = useMemo(() => program.missions.filter((mission) => mission.type === activeType), [activeType, program.missions]);
  const activeMission = program.missions.find((mission) => mission.id === activeMissionId && mission.type === activeType) ?? typeMissions[0] ?? null;

  function updateProgram(field: keyof ProgramRecord, value: string) { setProgram((current) => ({ ...current, [field]: value })); }
  function updateMission(id: string, field: keyof MissionRecord, value: string | number | string[]) { setProgram((current) => ({ ...current, missions: current.missions.map((mission) => mission.id === id ? { ...mission, [field]: value } : mission) })); }
  function chooseType(type: string) { setActiveType(type); setActiveMissionId(program.missions.find((mission) => mission.type === type)?.id || ""); }

  function addMission(type: string) {
    if (program.missions.length >= 12) return setNotice({ type: "error", text: "В одной программе может быть не больше 12 заданий." });
    const id = `new-${crypto.randomUUID()}`;
    const mission: MissionRecord = { id, ...typeCopy[type].template, sortOrder: program.missions.length, resources: [] };
    setProgram((current) => ({ ...current, missions: [...current.missions, mission] })); setActiveType(type); setActiveMissionId(id);
    setNotice({ type: "success", text: `Добавлено задание типа «${typeNames[type]}». Отредактируйте условия и сохраните программу.` });
  }

  async function removeMission(mission: MissionRecord) {
    if (!window.confirm(`Удалить задание «${mission.title}»? Отменить это действие после подтверждения нельзя.`)) return;
    if (program.missions.length <= 1) return setNotice({ type: "error", text: "В программе должно остаться хотя бы одно задание." });
    try {
      if (!mission.id.startsWith("new-")) { const response = await fetch(`/api/programs/${program.id}`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ missionId: mission.id }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "Не удалось удалить задание"); }
      const remaining = program.missions.filter((item) => item.id !== mission.id); setProgram((current) => ({ ...current, missions: current.missions.filter((item) => item.id !== mission.id) })); const next = remaining.find((item) => item.type === activeType) ?? remaining[0]; setActiveType(next.type); setActiveMissionId(next.id); setNotice({ type: "success", text: "Задание удалено." });
    } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Не удалось удалить задание" }); }
  }

  async function persist(action: "save" | "publish" | "pause") {
    setPending(action); setNotice(null);
    try {
      const response = await fetch(`/api/programs/${program.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...program, publish: action === "publish", pause: action === "pause", missions: program.missions }) }); const data = await response.json() as { status?: string; publicUrl?: string | null; error?: string; program?: ProgramRecord }; if (!response.ok || !data.status) throw new Error(data.error || "Не удалось сохранить программу");
      const saved = data.program ?? { ...program, status: data.status! }; setProgram(saved); setActiveMissionId(saved.missions.find((item) => item.title === activeMission?.title && item.type === activeType)?.id || saved.missions.find((item) => item.type === activeType)?.id || saved.missions[0]?.id || ""); setPublicUrl(data.publicUrl ?? null); setNotice({ type: "success", text: action === "publish" ? "Программа опубликована. Ссылка готова для агентов." : action === "pause" ? "Программа поставлена на паузу." : "Изменения сохранены." });
    } catch (reason) { setNotice({ type: "error", text: reason instanceof Error ? reason.message : "Не удалось сохранить программу" }); } finally { setPending(null); }
  }

  async function uploadResource(file: File) {
    if (!activeMission || activeMission.id.startsWith("new-")) return setNotice({ type: "error", text: "Сначала сохраните новое задание, затем приложите файл." });
    if (file.size > 10 * 1024 * 1024) return setNotice({ type: "error", text: "Файл должен быть не больше 10 МБ." });
    setFileBusy(true); setNotice(null);
    try { const form = new FormData(); form.set("file", file); const response = await fetch(`/api/programs/${program.id}/missions/${activeMission.id}/files`, { method: "POST", body: form }); const data = await response.json() as { resource?: MissionRecord["resources"][number]; error?: string }; if (!response.ok || !data.resource) throw new Error(data.error || "Не удалось загрузить файл"); setProgram((current) => ({ ...current, missions: current.missions.map((mission) => mission.id === activeMission.id ? { ...mission, resources: [...mission.resources, data.resource!] } : mission) })); setNotice({ type: "success", text: "Файл сохранён и уже доступен агентам." }); }
    catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Не удалось загрузить файл" }); } finally { setFileBusy(false); if (fileInput.current) fileInput.current.value = ""; }
  }

  async function removeResource(resourceId: string) { if (!activeMission || !window.confirm("Удалить файл из задания?")) return; const response = await fetch(`/api/programs/${program.id}/missions/${activeMission.id}/files?resource=${encodeURIComponent(resourceId)}`, { method: "DELETE" }); const data = await response.json() as { error?: string }; if (!response.ok) return setNotice({ type: "error", text: data.error || "Не удалось удалить файл" }); setProgram((current) => ({ ...current, missions: current.missions.map((mission) => mission.id === activeMission.id ? { ...mission, resources: mission.resources.filter((resource) => resource.id !== resourceId) } : mission) })); }
  async function copyLink() { if (publicUrl) { await navigator.clipboard.writeText(publicUrl); setNotice({ type: "success", text: "Публичная ссылка скопирована." }); } }
  async function prepareQr() { if (!publicUrl) return; const QRCode = await import("qrcode"); setQrUrl(await QRCode.toDataURL(publicUrl, { width: 900, margin: 2, color: { dark: "#171914", light: "#ffffff" } })); setShowQr(true); }
  async function downloadPoster() {
    if (!publicUrl) return; const QRCode = await import("qrcode"); const { PDFDocument } = await import("pdf-lib"); const qr = await QRCode.toDataURL(publicUrl, { width: 900, margin: 1, color: { dark: "#171914", light: "#ffffff" } });
    const canvas = document.createElement("canvas"); canvas.width = 1240; canvas.height = 1754; const context = canvas.getContext("2d"); if (!context) return; context.fillStyle = "#f4f2ea"; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = "#b8ff32"; context.fillRect(0, 0, canvas.width, 235); context.fillStyle = "#171914"; context.font = "800 42px Arial"; context.fillText("Relay", 90, 105); context.font = "700 24px Arial"; context.fillText("АГЕНТСКАЯ ПРОГРАММА", 90, 160); context.font = "700 58px Arial"; context.fillText(program.name.length > 36 ? `${program.name.slice(0, 34)}…` : program.name, 90, 330); context.font = "32px Arial"; context.fillText("Сканируйте QR-код и выберите задание", 90, 390);
    const image = new Image(); image.src = qr; await image.decode(); context.fillStyle = "#fff"; context.fillRect(170, 465, 900, 900); context.drawImage(image, 210, 505, 820, 820); context.fillStyle = "#171914"; context.font = "700 34px Arial"; context.textAlign = "center"; context.fillText(activeMission?.rewardLabel || program.missions[0]?.rewardLabel || "Получайте награды за полезные действия", 620, 1450); context.font = "25px Arial"; context.fillText("Условия, статус и выплата — в кабинете агента", 620, 1510); context.font = "20px Arial"; context.fillStyle = "#66685f"; context.fillText(new URL(publicUrl).host, 620, 1630);
    const pngBytes = await fetch(canvas.toDataURL("image/png")).then((response) => response.arrayBuffer()); const pdf = await PDFDocument.create(); const page = pdf.addPage([595.28, 841.89]); const png = await pdf.embedPng(pngBytes); page.drawImage(png, { x: 0, y: 0, width: 595.28, height: 841.89 }); const saved = await pdf.save(); const pdfBytes = saved.buffer.slice(saved.byteOffset, saved.byteOffset + saved.byteLength) as ArrayBuffer; downloadBlob(new Blob([pdfBytes], { type: "application/pdf" }), `relay-${program.slug}-qr.pdf`);
  }

  return <div className="dashboard-content module-content program-builder-page">
    <div className="builder-back"><Link href="/dashboard/programs">← Все программы</Link><span className={`program-status status-${program.status.toLowerCase()}`}>● {program.status === "ACTIVE" ? "Опубликована" : program.status === "PAUSED" ? "На паузе" : "Черновик"}</span></div>
    <div className="module-heading"><div><span className="module-kicker">НАСТРОЙКА ПРОГРАММЫ</span><h1>{program.name}</h1><p>Редактируйте один тип задания за раз — остальные остаются рядом и не перегружают экран.</p></div>{publicUrl && <div className="published-link-actions"><Link className="button button-ghost compact-button" href={publicUrl} target="_blank">Открыть страницу ↗</Link><button className="button button-ghost compact-button" type="button" onClick={prepareQr}>QR-код</button><button className="button button-primary compact-button" type="button" onClick={copyLink}>Копировать ссылку</button></div>}</div>
    <div className="builder-stepper"><span className="done"><b>✓</b>Основа</span><span className="active"><b>2</b>Задания и награды</span><span className={program.status === "ACTIVE" ? "done" : ""}><b>{program.status === "ACTIVE" ? "✓" : "3"}</b>Правила и публикация</span></div>{notice && <div className={`inline-notice ${notice.type}`} role="status">{notice.text}</div>}
    <section className="panel program-general-card"><div className="panel-header"><div><h2>Описание программы</h2><p>Коротко объясните агенту, что он может сделать и какой результат ожидается.</p></div></div><label className="builder-field"><span>Название</span><input value={program.name} onChange={(event) => updateProgram("name", event.target.value)} /></label><label className="builder-field"><span>Описание</span><textarea rows={4} value={program.description} onChange={(event) => updateProgram("description", event.target.value)} /></label><div className="builder-field-row"><label className="builder-field"><span>Цель</span><select value={program.goal} onChange={(event) => updateProgram("goal", event.target.value)}><option value="MIXED">Смешанная</option><option value="LEADS">Люди</option><option value="DEALS">Сделки</option><option value="BRAND">Имидж</option><option value="ENGAGEMENT">Вовлечение</option></select></label><label className="builder-field"><span>Валюта</span><select value={program.currency} onChange={(event) => updateProgram("currency", event.target.value)}><option>KZT</option><option>RUB</option><option>USD</option><option>EUR</option></select></label></div></section>
    <div className="mission-editor-heading"><div><span className="module-kicker">ШАГ 2</span><h2>Задания и награды</h2><p>Выберите тип — его рабочий модуль раскроется ниже.</p></div><span>{program.missions.length} заданий</span></div>
    <nav className="mission-type-cascade" aria-label="Типы заданий">{Object.entries(typeNames).map(([type, label]) => { const count = program.missions.filter((mission) => mission.type === type).length; return <button className={`type-${type.toLowerCase()} ${activeType === type ? "active" : ""}`} type="button" onClick={() => chooseType(type)} key={type}><i>{typeIcons[type]}</i><span><strong>{label}</strong><small>{typeCopy[type].summary}</small></span><b>{count}</b></button>; })}</nav>
    <section className={`mission-workspace type-${activeType.toLowerCase()}`}><header><div><span>{typeIcons[activeType]} {typeNames[activeType]}</span><h2>{typeCopy[activeType].summary}</h2></div><button type="button" onClick={() => addMission(activeType)}>＋ Добавить задание</button></header>{typeMissions.length > 0 && <div className="mission-tabs">{typeMissions.map((mission, index) => <button className={activeMission?.id === mission.id ? "active" : ""} type="button" onClick={() => setActiveMissionId(mission.id)} key={mission.id}><span>{String(index + 1).padStart(2, "0")}</span>{mission.title || "Без названия"}</button>)}</div>}
      {activeMission ? <article className="mission-focus-editor"><div className="mission-focus-head"><div><small>РЕДАКТИРОВАНИЕ ЗАДАНИЯ</small><strong>{activeMission.title || "Новое задание"}</strong></div><button className="mission-delete-button" type="button" onClick={() => void removeMission(activeMission)} aria-label="Удалить задание" title="Удалить задание">×</button></div><label className="builder-field"><span>Название задания</span><input value={activeMission.title} onChange={(event) => updateMission(activeMission.id, "title", event.target.value)} /></label><label className="builder-field"><span>{typeCopy[activeType].result}</span><textarea rows={4} value={activeMission.description} onChange={(event) => updateMission(activeMission.id, "description", event.target.value)} /></label><label className="builder-field"><span>Действия агента · по одному в строке</span><textarea rows={6} value={activeMission.instructions.join("\n")} onChange={(event) => updateMission(activeMission.id, "instructions", event.target.value.split("\n"))} /></label><label className="builder-field"><span>{typeCopy[activeType].proof} · по одному в строке</span><textarea rows={4} value={activeMission.proofRequirements.join("\n")} onChange={(event) => updateMission(activeMission.id, "proofRequirements", event.target.value.split("\n"))} /></label>
        <div className="mission-resource-box"><div><strong>Файл для агента</strong><p>Бриф, шаблон или пример до 10 МБ. Агент сможет скачать его из задания.</p></div><input ref={fileInput} type="file" hidden onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadResource(file); }} /><button type="button" disabled={fileBusy} onClick={() => fileInput.current?.click()}>{fileBusy ? "Загружаем…" : "＋ Загрузить файл"}</button>{activeMission.resources.length > 0 && <ul>{activeMission.resources.map((resource) => <li key={resource.id}><a href={`/api/programs/${program.id}/missions/${activeMission.id}/files?resource=${resource.id}`}>{resource.fileName} <small>{Math.max(1, Math.round(resource.size / 1024))} КБ</small></a><button type="button" onClick={() => void removeResource(resource.id)} aria-label={`Удалить ${resource.fileName}`}>×</button></li>)}</ul>}</div>
        <div className="reward-editor"><label className="builder-field"><span>Тип награды</span><select value={activeMission.rewardMode} onChange={(event) => updateMission(activeMission.id, "rewardMode", event.target.value)}><option value="FIXED">Фиксированная сумма</option><option value="PERCENT">Процент</option><option value="POINTS">Баллы</option><option value="NON_MONETARY">Неденежная</option></select></label><label className="builder-field"><span>Значение</span><input type="number" min="0" value={activeMission.rewardValue} onChange={(event) => updateMission(activeMission.id, "rewardValue", Number(event.target.value))} /></label></div><label className="builder-field"><span>Как награду увидит агент</span><input value={activeMission.rewardLabel} onChange={(event) => updateMission(activeMission.id, "rewardLabel", event.target.value)} placeholder={`Например: 25 000 ${program.currency}`} /></label><label className="builder-field"><span>Правила проверки</span><textarea rows={4} value={activeMission.verificationRules} onChange={(event) => updateMission(activeMission.id, "verificationRules", event.target.value)} /></label>
      </article> : <div className="mission-workspace-empty"><span>{typeIcons[activeType]}</span><h3>Заданий этого типа пока нет</h3><p>{typeCopy[activeType].summary}. Добавьте первое задание — остальные типы сохранятся без изменений.</p><button className="button button-primary" type="button" onClick={() => addMission(activeType)}>Добавить задание <span>＋</span></button></div>}
    </section>
    <section className="panel publication-card"><div className="panel-header"><div><span className="module-kicker">ШАГ 3</span><h2>Выплата, ограничения и публикация</h2><p>Эти условия видит агент до выполнения задания.</p></div></div><div className="publication-grid"><label className="builder-field"><span>Когда и как выплачивается награда</span><textarea rows={5} value={program.payoutTerms} onChange={(event) => updateProgram("payoutTerms", event.target.value)} /></label><label className="builder-field"><span>Юридические и этические ограничения</span><textarea rows={5} value={program.legalTerms} onChange={(event) => updateProgram("legalTerms", event.target.value)} /></label></div><label className="builder-field publication-date"><span>Дата завершения · необязательно</span><input type="date" value={program.expiresAt?.slice(0, 10) ?? ""} onChange={(event) => updateProgram("expiresAt", event.target.value)} /></label></section>
    <div className="program-publish-bar"><div><strong>{program.status === "ACTIVE" ? "Программа уже доступна агентам" : "Публикация создаст внешнюю ссылку"}</strong><p>Все изменения сохраняются только после нажатия кнопки.</p></div><div><button className="button button-ghost" type="button" onClick={() => persist("save")} disabled={pending !== null}>{pending === "save" ? "Сохраняем…" : "Сохранить"}</button>{program.status === "ACTIVE" ? <button className="button button-ghost" type="button" onClick={() => persist("pause")} disabled={pending !== null}>{pending === "pause" ? "Ставим на паузу…" : "Поставить на паузу"}</button> : <button className="button button-primary" type="button" onClick={() => persist("publish")} disabled={pending !== null}>{pending === "publish" ? "Публикуем…" : "Опубликовать программу"}<span>→</span></button>}</div></div>
    {showQr && <div className="relay-modal-backdrop"><button className="relay-modal-dismiss-layer" type="button" onClick={() => setShowQr(false)} aria-label="Закрыть QR-код" /><section className="relay-modal qr-program-modal" role="dialog" aria-modal="true" aria-labelledby="qr-title"><button className="relay-modal-close" type="button" onClick={() => setShowQr(false)} aria-label="Закрыть">×</button><span className="module-kicker">ОФЛАЙН-ПРИГЛАШЕНИЕ</span><h2 id="qr-title">QR-код программы</h2><p>Код ведёт прямо на публичную страницу «{program.name}».</p>{qrUrl && <img src={qrUrl} alt={`QR-код программы ${program.name}`} />}<strong>{activeMission?.rewardLabel || program.missions[0]?.rewardLabel}</strong><div><button className="button button-primary" type="button" onClick={() => void downloadPoster()}>Скачать A4 PDF</button><button className="button button-ghost" type="button" onClick={() => setShowQr(false)}>Готово</button></div></section></div>}
  </div>;
}
