"use client";

import { useMemo, useState } from "react";
import { formatDateTime, formatInteger } from "@/lib/format-display";

type Item = { id: string; partnerName: string; partnerEmail: string; partnerPhone: string; missionTitle: string; programName: string; rewardValue: number; rewardLabel: string; currency: string; contactName: string; contactCompany: string; contactEmail: string; contactPhone: string; partnerComment: string; companyComment: string; status: string; createdAt: string; attachments: Array<{ id: string; objectKey: string | null; externalUrl: string | null; fileName: string; mimeType: string; size: number }> };
const statuses = [["SUBMITTED", "Ждёт проверки"], ["REVIEWING", "Проверяется"], ["ACCEPTED", "Принят"], ["IN_PROGRESS", "В работе"], ["DEAL", "Сделка"], ["REWARDED", "Вознаграждение"], ["REJECTED", "Отклонён"]];
const actionStatuses = new Set(["SUBMITTED", "REVIEWING"]);

export function SubmissionReviewList({ initialItems }: { initialItems: Item[] }) {
  const [items, setItems] = useState(initialItems);
  const [selected, setSelected] = useState<Item | null>(null);
  const [pending, setPending] = useState("");
  const [notice, setNotice] = useState("");
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("ALL");
  const [programFilter, setProgramFilter] = useState("ALL");
  const [agentFilter, setAgentFilter] = useState("ALL");
  const programs = [...new Set(items.map((item) => item.programName))];
  const agents = [...new Map(items.map((item) => [item.partnerEmail, item.partnerName || item.partnerEmail])).entries()];
  const filtered = useMemo(() => items.filter((item) => {
    const haystack = `${item.partnerName} ${item.partnerEmail} ${item.programName} ${item.missionTitle} ${item.contactName} ${item.contactCompany} ${item.contactEmail} ${item.contactPhone}`.toLowerCase();
    return haystack.includes(query.trim().toLowerCase()) && (statusFilter === "ALL" || statusFilter === "ACTION" ? statusFilter !== "ACTION" || actionStatuses.has(item.status) : item.status === statusFilter) && (programFilter === "ALL" || item.programName === programFilter) && (agentFilter === "ALL" || item.partnerEmail === agentFilter);
  }).sort((left, right) => Number(actionStatuses.has(right.status)) - Number(actionStatuses.has(left.status)) || new Date(right.createdAt).getTime() - new Date(left.createdAt).getTime()), [items, query, statusFilter, programFilter, agentFilter]);

  async function update(item: Item, form: HTMLFormElement) {
    setPending(item.id); setNotice(""); const values = new FormData(form); const payload = { status: values.get("status"), comment: values.get("comment"), amount: values.get("amount"), currency: item.currency, plannedAt: values.get("plannedAt") };
    try { const response = await fetch(`/api/submissions/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "Не удалось сохранить решение"); const next = { ...item, status: String(payload.status), companyComment: String(payload.comment || ""), rewardValue: Number(payload.amount) || item.rewardValue }; setItems((current) => current.map((row) => row.id === item.id ? next : row)); setSelected(next); setNotice("Решение сохранено. Агент увидит новый статус и комментарий."); }
    catch (error) { setNotice(error instanceof Error ? error.message : "Ошибка"); } finally { setPending(""); }
  }

  if (!items.length) return null;
  return <div className="results-workspace">
    <div className="results-controls"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Агент, клиент или задание" aria-label="Поиск результата" /><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} aria-label="Статус"><option value="ALL">Все статусы</option><option value="ACTION">Требуют действия</option>{statuses.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><select value={programFilter} onChange={(event) => setProgramFilter(event.target.value)} aria-label="Программа"><option value="ALL">Все программы</option>{programs.map((program) => <option key={program}>{program}</option>)}</select><select value={agentFilter} onChange={(event) => setAgentFilter(event.target.value)} aria-label="Агент"><option value="ALL">Все агенты</option>{agents.map(([email, name]) => <option value={email} key={email}>{name}</option>)}</select></div>
    <div className="results-priority-line"><span><b>{filtered.filter((item) => actionStatuses.has(item.status)).length}</b> требуют решения</span><small>Показано {filtered.length} из {items.length}</small></div>{notice && <div className="inline-notice" role="status">{notice}</div>}
    <section className="result-card-list">{filtered.map((item) => <button className={`result-summary-card status-${item.status.toLowerCase()}`} type="button" onClick={() => { setSelected(item); setNotice(""); }} key={item.id}><span className="result-agent-avatar">{(item.partnerName || item.partnerEmail).slice(0,1).toUpperCase()}</span><span className="result-card-agent"><small>АГЕНТ</small><strong>{item.partnerName || item.partnerEmail}</strong><em>{item.programName}</em></span><span className="result-card-client"><small>{item.missionTitle}</small><strong>{item.contactName || "Результат без контакта"}</strong><em>{item.contactCompany || item.contactEmail || "Откройте детали"}</em></span><span className="result-card-reward"><small>ВОЗНАГРАЖДЕНИЕ</small><strong>{formatInteger(item.rewardValue)} {item.currency}</strong><em>{item.rewardLabel}</em></span><span className="result-card-status"><b>{statuses.find(([value]) => value === item.status)?.[1] ?? item.status}</b><small>{formatDateTime(item.createdAt)}</small></span><i aria-hidden="true">→</i></button>)}</section>
    {!filtered.length && <div className="table-empty">По выбранным условиям результатов нет.</div>}
    {selected && <div className="relay-modal-backdrop"><button className="relay-modal-dismiss-layer" type="button" onClick={() => setSelected(null)} aria-label="Закрыть результат" /><section className="relay-modal result-review-modal" role="dialog" aria-modal="true" aria-labelledby="result-modal-title"><button className="relay-modal-close" type="button" onClick={() => setSelected(null)} aria-label="Закрыть">×</button><div className="result-modal-heading"><span>{selected.programName} · {selected.missionTitle}</span><h2 id="result-modal-title">{selected.contactName || "Результат задания"}</h2><p>Передал {selected.partnerName} · {formatDateTime(selected.createdAt)}</p></div><div className="result-modal-grid"><div><small>АГЕНТ</small><strong>{selected.partnerName}</strong><a href={`mailto:${selected.partnerEmail}`}>{selected.partnerEmail}</a></div><div><small>КЛИЕНТ / РЕЗУЛЬТАТ</small><strong>{selected.contactCompany || "Компания не указана"}</strong><span>{selected.contactEmail || "Email не указан"}</span></div><div><small>ТЕЛЕФОН КЛИЕНТА</small>{selected.contactPhone ? <a href={`https://wa.me/${selected.contactPhone.replace(/\D/g, "")}?text=${encodeURIComponent(`Здравствуйте! Ваш контакт мне передал агент ${selected.partnerName} через Relay.`)}`} target="_blank" rel="noreferrer">{selected.contactPhone} ↗</a> : <strong>Не указан</strong>}</div><div><small>ОЖИДАЕМАЯ НАГРАДА</small><strong>{formatInteger(selected.rewardValue)} {selected.currency}</strong><span>{selected.rewardLabel}</span></div></div><div className="result-context"><small>КОММЕНТАРИЙ АГЕНТА</small><p>{selected.partnerComment || "Комментарий не оставлен"}</p></div>{selected.attachments.length > 0 && <div className="result-attachments"><span>ФАЙЛЫ И ССЫЛКИ АГЕНТА</span><div>{selected.attachments.map((attachment) => <a href={attachment.externalUrl || `/api/company/files/${attachment.id}`} target="_blank" rel="noreferrer" key={attachment.id}><i>{attachment.externalUrl ? "↗" : "↓"}</i><span><b>{attachment.fileName}</b><small>{attachment.externalUrl ? "Внешняя ссылка" : `${Math.max(1, Math.round(attachment.size / 1024))} КБ`}</small></span></a>)}</div></div>}
      <form className="result-decision-form" onSubmit={(event) => { event.preventDefault(); void update(selected, event.currentTarget); }}><label><span>Статус</span><select name="status" defaultValue={selected.status}>{statuses.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label><span>Сумма награды</span><input name="amount" type="number" min="0" defaultValue={selected.rewardValue} /></label><label><span>Плановая выплата</span><input name="plannedAt" type="date" /></label><label className="review-comment"><span>Комментарий агенту</span><textarea name="comment" defaultValue={selected.companyComment} rows={4} placeholder="Объясните решение. При отказе комментарий обязателен." /></label><button type="submit" disabled={pending === selected.id}>{pending === selected.id ? "Сохраняем…" : "Сохранить решение"}</button>{selected.partnerPhone && <a href={`https://wa.me/${selected.partnerPhone.replace(/\D/g, "")}?text=${encodeURIComponent(`Здравствуйте, ${selected.partnerName}! Компания обновила статус результата «${selected.missionTitle}» в Relay.`)}`} target="_blank" rel="noreferrer">Уведомить агента в WhatsApp ↗</a>}</form></section></div>}
  </div>;
}
